### PR TITLE
[Task] Update README :tada:

### PR DESCRIPTION
**Pull request by skrix**

### CODE REVIEW

**Comment by andrzejkrzywda** [comment]
Great job with the README @skrix , you nailed it with the vision description!

Is the gemset change meant to be part of this PR? Do we need it?

**Comment by skrix** [comment]
> Is the gemset change meant to be part of this PR? Do we need it?
Added btw, using it locally and think it can be useful for others to not override dependencies

**Comment by andrzejkrzywda** [comment]
I'm merging this, but I'm still not sure if the gemset should be part of the repo. Not everyone has to use rvm/gemsets to use it. It's better to probably keep it private per developer.

**Comment by andrzejkrzywda** [comment]
Thanks for the great README 👍

**Pull request merged**
